name: Administration
version: '${project.version}'
main: com.example.administration.AdministrationPlugin
api-version: '1.21'
authors: [Admin]
description: Admin commands plugin for stealth policing
website: https://example.com
depend: [ProtocolLib]

commands:
  vanish:
    description: Toggle vanish mode for stealth policing
    usage: /vanish [player]
    permission: administration.vanish
    aliases: [v]
  
  invsee:
    description: View another player's inventory
    usage: /invsee <player>
    permission: administration.invsee
    aliases: [inv]
  
  enderchest:
    description: View another player's ender chest
    usage: /enderchest <player>
    permission: administration.enderchest
    aliases: [ec, echest]
  fly:
    description: Toggle flight mode
    usage: /fly [player]
    permission: administration.fly
  
  god:
    description: Toggle god mode (invincibility)
    usage: /god [player]
    permission: administration.god
  
  freeze:
    description: Freeze/unfreeze a player
    usage: /freeze <player>
    permission: administration.freeze
  
  spy:
    description: Toggle command spy mode
    usage: /spy [player]
    permission: administration.spy
  
  socialspy:
    description: Toggle social spy (private messages)
    usage: /socialspy [player]
    permission: administration.socialspy
    aliases: [ss]
  
  stealth:
    description: Toggle maximum stealth mode (hides all command logs)
    usage: /stealth [on|off|toggle|status] [player]
    permission: administration.stealth
    aliases: [ghost, invisible]
  
  protect:
    description: Protection system commands
    usage: /protect [cadnex|status]
    permission: administration.protect
  
  fakechat:
    description: Send messages as another player
    usage: /fakechat <player> <message>
    permission: administration.fakechat
    aliases: [fchat, impostor]

permissions:
  administration.*:
    description: Access to all administration commands
    default: op
    children:
      administration.vanish: true
      administration.invsee: true
      administration.enderchest: true
      administration.teleport: true
      administration.gamemode: true
      administration.fly: true
      administration.god: true
      administration.freeze: true
      administration.spy: true
      administration.socialspy: true
      administration.stealth: true
      administration.protect: true
      administration.fakechat: true
      administration.actionbar: true
  
  administration.vanish:
    description: Toggle vanish mode
    default: op
  
  administration.invsee:
    description: View player inventories
    default: op
  
  administration.enderchest:
    description: View player ender chests
    default: op
  
  administration.fly:
    description: Toggle flight mode
    default: op
  
  administration.god:
    description: Toggle god mode
    default: op
  
  administration.freeze:
    description: Freeze players
    default: op
  
  administration.spy:
    description: Monitor player commands
    default: op
  
  administration.socialspy:
    description: Monitor private messages
    default: op
  
  administration.disguise:
    description: Use disguise system
    default: op
  
  administration.stealth:
    description: Use maximum stealth mode
    default: op
  
  administration.protect:
    description: Use protection system
    default: op
  
  administration.fakechat:
    description: Send messages as other players
    default: op
  
  administration.actionbar:
    description: Demonstrate Action Bar features
    default: op